### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by caicancai**
I will complete the readme document tonight, please don't merge it yet

### CODE REVIEW

**Review by ethe — APPROVED** [review]
LGTM

**Comment by caicancai** [comment]
> LGTM


@ethe Hi, Do you plan to write a separate document about how to build, or explain it in the readme?

**Comment by ethe** [comment]
Yes indeed, maybe just github wiki at first?

**Comment by caicancai** [comment]
> Yes indeed, maybe just github wiki at first?

OK, this PR is ready. I was thinking about whether to add how to build in the readme.

**Comment by ethe** [comment]
Thank you! Wish there are more collaborations in the future 😄

**Pull request merged**
