### PR TITLE
chore: add more unit tests

### PR DESCRIPTION
**Pull request by caicancai**

### CODE REVIEW

**Comment by caicancai** [comment]
@ethe
image
I don't know why this error is reported. Does the test file need a main method? I can execute it locally.
image

**Comment by Kilerd** [comment]
> @ethe Hi
> 
> image
> I don't know why this error is reported. Does the test file need a main method? I can execute it locally.
> 
> image

Hey @caicancai 
each trybuild test file need a `main` function, cuz `trybuild` will compile each file as a independent project. 
If the `main` function is missing, a compile error occurs by rustc.

**Comment by caicancai** [comment]
@Kilerd Thanks for your answer. I just started learning Rust and it's not very clear. I will fix it later.

**Comment by Kilerd** [comment]
And I think the folder `test` is only for the compile test, not for unit tests. probably you need to move your test under src folder ?

**Comment by caicancai** [comment]
Perhaps the examples file is a good place to do this.

**Comment by Kilerd** [comment]
it make sense, then I think we need to regroup the testfiles in `test` folder, and separate them into multiple sub folder, like `integration_test` and `compile_test`, to clarify.

**Comment by caicancai** [comment]
> it make sense, then I think we need to regroup test files in `test` folder, and separate them into multiple sub folder, like `integration_test` and `compile_test`, for clarification.

yes, good idea

**Comment by caicancai** [comment]
Close this PR first, discuss where the unit test should be placed first, I will open an issue

**Pull request closed without merging**
